### ISSUE TITLE
[2.23] update-stylesheets - (SystemCallError) Unknown error - uri:classloader:/ in racc-1.4.14-java.gemspec

### ISSUE THREAD

**Issue by agabrys** [GeoDienstenCentrum/sass-maven-plugin#149]
Sometimes we get a build failure on the CI server:

> Execution default of goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets failed: (SystemCallError) Unknown error - uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/specifications/default/racc-1.4.14-java.gemspec -> [Help 1]

This is a rarely error - once per 30-40 builds.

### Actual Behavior
Maven command:
```
mvn -e install -DskipTests
```

Logs:
```
18:37:02 [ERROR] Failed to execute goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets (default) on project abc-widgets: Execution default of goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets failed: (SystemCallError) Unknown error - uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/specifications/default/racc-1.4.14-java.gemspec -> [Help 1]
18:37:02 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets (default) on project backoffice-widgets: Execution default of goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets failed: (SystemCallError) Unknown error - uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/specifications/default/racc-1.4.14-java.gemspec
18:37:02 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
18:37:02 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
18:37:02 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
18:37:02 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
18:37:02 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
18:37:02 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
18:37:02 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
18:37:02 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
18:37:02 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
18:37:02 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
18:37:02 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
18:37:02 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
18:37:02 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:37:02 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:37:02 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:37:02 	at java.lang.reflect.Method.invoke(Method.java:498)
18:37:02 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
18:37:02 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
18:37:02 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
18:37:02 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
18:37:02 Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets failed: (SystemCallError) Unknown error - uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/specifications/default/racc-1.4.14-java.gemspec
18:37:02 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
18:37:02 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
18:37:02 	... 19 more
18:37:02 Caused by: org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error - uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared/specifications/default/racc-1.4.14-java.gemspec
18:37:02 	at org.jruby.RubyIO.read(org/jruby/RubyIO.java:2993)
18:37:02 	at org.jruby.RubyIO.read(org/jruby/RubyIO.java:2977)
18:37:02 	at org.jruby.RubyIO.read(org/jruby/RubyIO.java:3592)
18:37:02 	at RUBY.load(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1156)
18:37:02 	at RUBY.block in each_spec(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:820)
18:37:02 	at RUBY.block in each_gemspec(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:743)
18:37:02 	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1733)
18:37:02 	at RUBY.block in each_gemspec(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:742)
18:37:02 	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1733)
18:37:02 	at RUBY.each_gemspec(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:741)
18:37:02 	at RUBY.each_spec(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:819)
18:37:02 	at RUBY.load_defaults(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:871)
18:37:02 	at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:1362)
18:37:02 	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
18:37:02 	at RUBY.<main>(uri:classloader:/jruby/kernel/gem_prelude.rb:1)
18:37:02 	at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:979)
18:37:02 	at RUBY.<main>(uri:classloader:/jruby/kernel/gem_prelude.rb:3)
18:37:02 [ERROR] 
18:37:02 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
18:37:02 [ERROR] 
18:37:02 [ERROR] For more information about the errors and possible solutions, please read the following articles:
18:37:02 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
18:37:02 [ERROR] 
18:37:02 [ERROR] After correcting the problems, you can resume the build with the command
18:37:02 [ERROR]   mvn <goals> -rf :abc-widgets
```

### Environment and configuration
```
<plugin>
	<groupId>nl.geodienstencentrum.maven</groupId>
	<artifactId>sass-maven-plugin</artifactId>
	<version>2.23</version>
	<executions>
		<execution>
			<goals>
				<goal>update-stylesheets</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<sassSourceDirectory>src/main/resources/sass</sassSourceDirectory>
		<destination>${project.build.directory}/classes/sass</destination>
		<skip>false</skip>
		<sassOptions>
			<always_update>true</always_update>
			<sourcemap>:none</sourcemap>
			<load_paths>['${basedir}/${root.project.relative.path}abc-base/acbframework/src/main/resources/sass/abc/scss']</load_paths>
		</sassOptions>
	</configuration>
</plugin>
```

```
$ mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /usr/lib/jvm/oracle-java8-jdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-4-amd64", arch: "amd64", family: "unix"
```

```
$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

```
$ uname -a
Linux host-d-8668 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
```

**Comment by mprins** [comment]
You probably want to take this up with the jruby and/or race team. It's likely a memory issue

**Comment by agabrys** [comment]
Ok, I created an issue in ruby backolog (jruby/jruby#4402).

**Comment by mprins** [comment]
closing as this was closed upstream and identified as probably memory issues
