### ISSUE TITLE
JRuby exception "Errno::ESRCH" on updating stylesheets (sass-maven-plugin v2.1)

### ISSUE THREAD

**Issue by StefanLiebenberg** [GeoDienstenCentrum/sass-maven-plugin#24]
Using this plugin with the configuration:

     <plugin>
                <groupId>nl.geodienstencentrum.maven</groupId>
                <artifactId>sass-maven-plugin</artifactId>
                <version>2.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>update-stylesheets</goal>
                        </goals>
                        <phase>generate-resources</phase>
                    </execution>
                </executions>
                <configuration>
                    <sassSourceDirectory>src/main/stylesheets</sassSourceDirectory>
                    <destination>${project.build.directory}/css/</destination>
                    <useCompass>true</useCompass>
                    <sassOptions>
                        <style>:compressed</style>
                    </sassOptions>
                </configuration>
            </plugin>

Produces the exception on windows:

    Sass::Plugin.update_stylesheets
            at nl.geodienstencentrum.maven.plugin.sass.AbstractSassMojo.executeSassScript(AbstractSassMojo.java:237)
                at nl.geodienstencentrum.maven.plugin.sass.compiler.UpdateStylesheetsMojo.execute(UpdateStylesheetsMojo.java:52)
                at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
                ... 19 more
        Caused by: javax.script.ScriptException: org.jruby.embed.EvalFailedException: (Errno::ESRCH) C:/workspace/repository/target/css/style.css
                at org.jruby.embed.jsr223.JRubyEngine.wrapException(JRubyEngine.java:104)
                at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:93)
                at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
                at nl.geodienstencentrum.maven.plugin.sass.AbstractSassMojo.executeSassScript(AbstractSassMojo.java:231)
                ... 22 more
        Caused by: org.jruby.embed.EvalFailedException: (Errno::ESRCH) C:/workspace/repository/target/css/style.css
                at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
                at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
                ... 24 more
        Caused by: org.jruby.exceptions.RaiseException: (Errno::ESRCH) C:/workspace/repository/target/css/style.css
                at org.jruby.RubyFile.mtime(org/jruby/RubyFile.java:941)
                at RUBY.stylesheet_needs_update?(C:/Users/user/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.1/sass-maven-plugin-2.1.jar!/gems/sass-3.4.10/lib/sass/plugin/staleness_checker.rb:65)
                at RUBY.update_stylesheets(C:/Users/user/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.1/sass-maven-plugin-2.1.jar!/gems/sass-3.4.10/lib/sass/plugin/compiler.rb:211)
                at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
                at RUBY.update_stylesheets(C:/Users/user/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.1/sass-maven-plugin-2.1.jar!/gems/sass-3.4.10/lib/sass/plugin/compiler.rb:209)
                at RUBY.update_stylesheets(C:/Users/user/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.1/sass-maven-plugin-2.1.jar!/gems/sass-3.4.10/lib/sass/plugin.rb:82)
                at RUBY.(root)(<script>:30)

Switching to 2.0 solved the issue.

**Comment by mprins** [comment]
jruby/jruby#2498 may be related

**Comment by StefanLiebenberg** [comment]
wouldn't this occur in 2.0 as well then?

**Comment by mprins** [comment]
@StefanLiebenberg the big change from 2.0 to 2.1 is the update of JRuby (1.6.8 to 1.7.18). There are some issues in the current JRuby especially where file attributes and access are concerned. 
Your stacktrace references the mtime() function where sass tries to determine if a file should be updated.

You may be able to work around this using the `always_update` option.

see 
https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/test/projects/maven-compass-resources-test/pom.xml#L59 
for an example

**Comment by mprins** [comment]
also, you may be able to override the jruby dependency of the plugin, that would look something like:

```xml
 <plugin>
        <groupId>nl.geodienstencentrum.maven</groupId>
        <artifactId>sass-maven-plugin</artifactId>
        <version>2.1</version>
        <dependencies>
                 <dependency>
			<groupId>org.jruby</groupId>
			<artifactId>jruby-complete</artifactId>
			<version>1.7.15</version>
		  </dependency>
....

```

this blogpost: http://blog.sonatype.com/2008/04/how-to-override-a-plugins-dependency-in-maven/ talks about that. You need to experiment with the jruby version number, the bug report I mentioned above lists 1.7.15 as working OK.. YMMV

**Comment by mprins** [comment]
@StefanLiebenberg I'm curious if this is still an issue with version 2.9-RC1 that I just created/released which has the new JRuby engine (9000) and a current version of Sass

**Comment by knutsiem** [comment]
@mprins This is unfortunately still an issue with 2.23 and JRuby 9.1.8.0. I'm running Maven 3.2.5 with the following configuration.

```xml
      <plugin>
        <groupId>nl.geodienstencentrum.maven</groupId>
        <artifactId>sass-maven-plugin</artifactId>
        <version>2.23</version>
        <executions>
          <execution>
            <goals>
              <goal>update-stylesheets</goal>
            </goals>
            <configuration>
              <sassOptions>
                <!-- Turning off always_update to run incremental builds faster -->
                <always_update>false</always_update>

                <!-- Restate other plugin defaults which would be lost otherwise -->
                <cache>true</cache>
                <unix_newlines>true</unix_newlines>
                <style>:expanded</style>
              </sassOptions>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.jruby</groupId>
            <artifactId>jruby-complete</artifactId>
            <version>9.1.8.0</version>
          </dependency>
        </dependencies>
      </plugin>
```
You're right about this triggered by `always_update` -- setting it to true makes the build succeed. However, I'd like to avoid rebuilding all templates just because one changed. @StefanLiebenberg's configuration also has `always_update` set to `false`, although implicitly.

I realize that this is an old issue, but I'm commenting here because as far as I can tell the problem is the same as initially reported.

[jnr/jnr-posix#61 paths past the first ENOENT on windows using stat will return ESRCH](https://github.com/jnr/jnr-posix/issues/61) reports this _JRuby problem_ more precisely. 

A Maven workaround that let's me keep `always_update` `false` is to create the directories manually upfront using e.g. Maven AntRun Plugin (while also configuring Sass Maven Plugin with `<destination>${sass.outputDirectory}</destination>`).

```xml
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.8</version>
        <executions>
          <execution>
            <!-- Workaround: Necessary because Sass Maven Plugin doesn't create
              the output directories by itself and if using analyze_only without
              it, the Sass compiler will fail (at least on Windows) -->
            <id>create-sass-output-dir</id>
            <phase>initialize</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <tasks>
                <mkdir dir="${sass.outputDirectory}" />
              </tasks>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

Knowing that this low-level problem exists, is creating the necessary output directories in the plugin an option?

**Comment by mprins** [comment]
I really don't want to add that kind (ie. OS and config specific) of hacks to the code, especially since it can be fixed by configuration.
Also it is the task of Sass to create the directories during a build and not this plugin which merely constructs a script calling into Sass.

**Comment by knutsiem** [comment]
I completely understand. Let's hope jnr/jnr-posix#61 gets some attention.
