### ISSUE TITLE
build fails, no such file: sass-maven-plugin/2.12/sass-maven-plugin-2.12.jar!/specifications/compass-import-once-1.0.5.gemspec

### ISSUE THREAD

**Issue by Kuerten** [GeoDienstenCentrum/sass-maven-plugin#79]
The maven build (mvn compile) fails with the following error:

```
[INFO] --- sass-maven-plugin:2.12:update-stylesheets (compile-scss) @ gui-base ---
[INFO] Checked 31 files for C:\eclipse-workspaces\eclipse-workspace-dev\supernova-aggregate\gui-base\src\main\webapp\css\src
[INFO] Checked 0 files for C:\eclipse-workspaces\eclipse-workspace-dev\supernova-aggregate\gui-base\target\classes\META-INF-resources\css
[INFO] Compiling Sass templates
[INFO] No resource element was specified, using short configuration.
[INFO] Queueing Sass template for compile: C:/eclipse-workspaces/eclipse-workspace-dev/supernova-aggregate/gui-base/src/main/webapp/css/src => C:/eclipse-workspaces/eclipse-workspace-dev/supernova-aggregate/gui-base/target/classes/META-INF-resources/css
Errno::ENOENT: No such file or directory - file:/C:/Users/Kürten/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.12/sass-maven-plugin-2.12.jar!/specifications/compass-import-once-1.0.5.gemspec
             initialize at org/jruby/RubyFile.java:342
                   open at org/jruby/RubyIO.java:1124
                   open at org/jruby/RubyKernel.java:311
                   data at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/stub_specification.rb:75
                 valid? at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/stub_specification.rb:178
     block in each_stub at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:731
  block in each_gemspec at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:723
                   each at org/jruby/RubyArray.java:1560
  block in each_gemspec at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:722
                   each at org/jruby/RubyArray.java:1560
           each_gemspec at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:721
              each_stub at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:729
                  stubs at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:748
  find_inactive_by_path at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:936
           try_activate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:187
                require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:126
                  <top> at <script>:6
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.606 s
[INFO] Finished at: 2015-09-16T17:43:37+02:00
[INFO] Final Memory: 48M/480M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal nl.geodienstencentrum.maven:sass-maven-plugin:2.12:update-stylesheets (compile-scss) on project gui-base: Failed to execute Sass ruby script:
[ERROR] require 'rubygems'
[ERROR] env = { 'GEM_PATH' => [
[ERROR] 'C:\eclipse-workspaces\eclipse-workspace-dev\supernova-aggregate\gui-base\target/rubygems'
[ERROR] ] }
[ERROR] Gem.paths = env
[ERROR] require 'sass/plugin'
[ERROR] require 'java'
[ERROR] Sass::Plugin.options.merge!(
[ERROR] :css_location => 'C:/eclipse-workspaces/eclipse-workspace-dev/supernova-aggregate/gui-base/target/classes/META-INF-resources/css',
[ERROR] :cache => true,
[ERROR] :always_update => true,
[ERROR] :template_location => 'C:/eclipse-workspaces/eclipse-workspace-dev/supernova-aggregate/gui-base/src/main/webapp/css/src',
[ERROR] :cache_location => 'C:/eclipse-workspaces/eclipse-workspace-dev/supernova-aggregate/gui-base/target/sass_cache',
[ERROR] :unix_newlines => true,
[ERROR] :style => :expanded
[ERROR] )
[ERROR] Sass::Plugin.on_compilation_error {|error, template, css| $compiler_callback.compilationError(error.message, template, css) }
[ERROR] Sass::Plugin.on_updated_stylesheet {|template, css| $compiler_callback.updatedStylesheeet(template, css) }
[ERROR] Sass::Plugin.on_template_modified {|template| $compiler_callback.templateModified(template) }
[ERROR] Sass::Plugin.on_template_created {|template| $compiler_callback.templateCreated(template) }
[ERROR] Sass::Plugin.on_template_deleted {|template| $compiler_callback.templateDeleted(template) }
[ERROR] Sass::Plugin.update_stylesheets: org.jruby.embed.EvalFailedException: (Errno::ENOENT) file:/C:/Users/Kürten/.m2/repository/nl/geodienstencentrum/maven/sass-maven-plugin/2.12/sass-maven-plugin-2.12.jar!/specifications/compass-import-once-1.0.5.gemspec
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
The configuration is:
```xml
      <plugin>
        <groupId>nl.geodienstencentrum.maven</groupId>
        <artifactId>sass-maven-plugin</artifactId>
        <version>2.12</version>
        <executions>
          <execution>
            <id>compile-scss</id>
            <phase>compile</phase>
            <goals>
              <goal>update-stylesheets</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <sassSourceDirectory>${project.basedir}/src/main/webapp/css/src/</sassSourceDirectory>
          <destination>${project.build.directory}/classes/META-INF/resources/css2/</destination>
          <useCompass>false</useCompass>
          <!--skip>true</skip-->
        </configuration>
      </plugin>
```

**Comment by mprins** [comment]
Can you see if moving the maven repository to a directory without an umlaut in the name helps? (see https://maven.apache.org/guides/mini/guide-configuring-maven.html)

Also you may want to try the 2.13-SNAPSHOT version (which has the latest JRuby runtime), you'll need to add the snapshot  (see https://github.com/mprins/maven-compass-example/blob/master/pom.xml#L42)

I've added a testcase to try and reproduce this error in 276603f6eaaf8db2fc6fd8863c28fc97ba9cbce5

and it seems to be failing on windows (https://ci.appveyor.com/project/mprins/sass-maven-plugin/build/468%20(umlaut-directory)/job/f0mtxtyhrbyk9gry#L866)
(but not on mac or unix  https://travis-ci.org/GeoDienstenCentrum/sass-maven-plugin/builds/81354866)

also locally I'm seeing the following on a win7 VM
```
/*
Error: File to import not found or unreadable: KÃ¼rten/colours.
       Load path: C:/workspace/sass-maven-plugin/target/test-projects/UpdateStylesheetsMojoTest_testCompile_maven_sass_umlaut_test_maven-sass-umlaut-test/src/main/sass
        on line 1 of C:/workspace/sass-maven-plugin/target/test-projects/UpdateStylesheetsMojoTest_testCompile_maven_sass_umlaut_test_maven-sass-umlaut-test/src/main/sass/compiled.scss

1: @import 'KÃ¼rten/colours';
2: @import 'KÃ¼rten/style';

Backtrace:
C:/workspace/sass-maven-plugin/target/test-projects/UpdateStylesheetsMojoTest_testCompile_maven_sass_umlaut_test_maven-sass-umlaut-test/src/main/sass/compiled.scss:1
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/import_node.rb:67:in `import'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/import_node.rb:28:in `imported_file'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/import_node.rb:35:in `css_import?'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:311:in `visit_import'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/base.rb:36:in `visit'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
uri:classloader:/gems/sass-3.4.18/lib/sass/stack.rb:79:in `block in with_base'
uri:classloader:/gems/sass-3.4.18/lib/sass/stack.rb:115:in `with_frame'
uri:classloader:/gems/sass-3.4.18/lib/sass/stack.rb:79:in `with_base'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:158:in `visit'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
org/jruby/RubyArray.java:2300:in `map'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/base.rb:52:in `visit_children'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/base.rb:36:in `block in visit'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/base.rb:36:in `visit'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:158:in `visit'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/visitors/perform.rb:8:in `visit'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/root_node.rb:36:in `css_tree'
uri:classloader:/gems/sass-3.4.18/lib/sass/tree/root_node.rb:29:in `render_with_sourcemap'
uri:classloader:/gems/sass-3.4.18/lib/sass/engine.rb:378:in `_render_with_sourcemap'
uri:classloader:/gems/sass-3.4.18/lib/sass/engine.rb:295:in `render_with_sourcemap'
uri:classloader:/gems/sass-3.4.18/lib/sass/plugin/compiler.rb:490:in `update_stylesheet'
uri:classloader:/gems/sass-3.4.18/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
org/jruby/RubyArray.java:1560:in `each'
uri:classloader:/gems/sass-3.4.18/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
uri:classloader:/gems/sass-3.4.18/lib/sass/plugin.rb:82:in `update_stylesheets'
<script>:21:in `<top>'
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Error: File to import not found or unreadable: KÃ¼rten/colours.\A        Load path: C:/workspace/sass-maven-plugin/target/test-projects/UpdateStylesheetsMojoTest_testCompile_maven_sass_umlaut_test_maven-sass-umlaut-test/src/main/sass\A         on line 1 of C:/workspace/sass-maven-plugin/target/test-projects/UpdateStylesheetsMojoTest_testCompile_maven_sass_umlaut_test_maven-sass-umlaut-test/src/main/sass/compiled.scss\A \A 1: @import 'KÃ¼rten/colours';\A 2: @import 'KÃ¼rten/style';"; }
```

**Comment by Kuerten** [comment]
I moved the maven repository to a different path and now the compilation succeeds. So most likely is was the german umlaut in the path name.
I did not try the snapshot yet.
For me the issue is solved, but you may want to add this to documentation.

**Comment by mprins** [comment]
OK, I will leave this open untill I add a note somewhere.

I don't think the snapshot would have helped here anyways...
